### ISSUE TITLE
Set new values to labels

### ISSUE THREAD

**Issue by kmergen** [soap/yii2-language-switcher#2]
Is there a possibility to set new items to labels ?

**Comment by soap** [comment]
Sorry I didn't see your issue. And I didn't quite clear about your requirement. Can you explain more.

**Comment by soap** [comment]
Flag label can be added in application configuration
![image](https://user-images.githubusercontent.com/1073690/125248949-e4ad0380-e31e-11eb-9330-b692bd9dff68.png)

**Comment by soap** [comment]
Please add your application default language and add it UrlManager too.

![image](https://user-images.githubusercontent.com/1073690/125249074-0312ff00-e31f-11eb-8836-677601d6a5c3.png)
Please consult for codemix 's UrlManager documentation.
